# Generated by Django 5.1.4 on 2025-01-28 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('0ee7fea8-e61d-4475-a7ff-fb7a84b5ad06'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.CharField(choices=[('I', 'IN_STOCK'), ('R', 'RUNNING_OUT_OF_STOCK'), ('P', 'PREORDER')], max_length=15),
        ),
    ]
