# Generated by Django 5.1.4 on 2025-01-28 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_product_id_alter_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(default='static/category-default-image.png', upload_to='media/category_icons'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('230e073b-e6a5-4130-b000-995df7ddd93e'), editable=False, null=True),
        ),
    ]
