# Generated by Django 5.1.4 on 2025-01-28 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_category_icon_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(upload_to='media/category_icons'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('35b04d58-4fc4-425a-bb53-4e46a9096b53'), editable=False, null=True),
        ),
    ]
