# Generated by Django 5.1.4 on 2025-01-28 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('c49e38fe-6782-4628-a658-5dca7e49f83b'), editable=False, null=True),
        ),
    ]
