# Generated by Django 5.1.4 on 2025-01-28 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(null=True, upload_to='media/category_icons'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('9e7b5a14-da1b-49df-b353-48ed41f179d5'), editable=False, null=True),
        ),
    ]
