# Generated by Django 5.1.4 on 2025-01-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
