# Generated by Django 5.1.4 on 2025-01-29 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_productimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
