# Generated by Django 5.1.4 on 2025-01-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
