# Generated by Django 5.1.4 on 2025-01-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_category_id_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='test',
        ),
    ]
