name: Deploy Frontend to Railway
on:
  push:
    paths:
      - 'frontend/**' # Trigger only if changes occur in the frontend directory
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Frontend to Railway
        uses: railwayapp/cli-action@v1
        with:
          service: frontend
          token: ${{ secrets.RAILWAY_TOKEN }}
